# Generated by Django 5.2.3 on 2025-06-18 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_initial'),
        ('subscriptions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorpremiumsubscriptionpayment',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_subscription_payments', to='users.tutor'),
        ),
        migrations.AddField(
            model_name='tutorpremiumsubscriptionpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_premium_subscription_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpremiumsubscriptionpayment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_premium_subscription_payments', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='userpremiumsubscriptionpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_premium_subscription_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
