"""
Django settings for cp_login project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os,sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8pn!0qthqdvn9syj382&wlk#thve#*%8qf&&f8p@x5_qahc5za'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['081e-106-51-161-101.ngrok-free.app','127.0.0.1','localhost' ]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'scheduling_stripe',
    'rest_framework',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'social_django',  # Add social auth app  
    'tutor_courses',
    'payments',
    'django_celery_results',
    'live_class_streaming',
    'simple_history',
    'import_export',
        
]

SITE_ID = 1

MIDDLEWARE = [
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'cp_login.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cp_login.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {
    "site_title": "CampusPlatz Admin",
    "site_header": "CampusPlatz Administration",
    "site_brand": "CampusPlatz Admin",
    "welcome_sign": "Welcome to CampusPlatz Admin",
    "copyright": "CampusPlatz", }

JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg", } # Choose from: darkly, cyborg, superhero, slate

#Google OAuth2
GOOGLE_CLIENT_ID='84178167567-gk26or49o3vfaaui19bb4ca5l1181734.apps.googleusercontent.com'
GOOGLE_OAUTH2_SECRET='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'
GOOGLE_OAUTH2_REDIRECT_URI='http://localhost:8000/auth/google/callback/'
GOOGLE_OAUTH2_SCOPE = ['email', 'profile']

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
]


# CORS settings 
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000", 
    "http://127.0.0.1:5500",
    "http://localhost:5500",

   
]


SIMPLE_JWT = {
    'USER_ID_FIELD': 'email',  # Use email as the user identifier
    'USER_ID_CLAIM': 'email',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


STRIPE_SECRET_KEY = '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'
STRIPE_PUBLIC_KEY = 'pk_live_51R5TuGEb88xTWu1L8jgVgnRgxFhOkVsWJIFclAitRbj8S1jkkwA4IX7sdvJYwu2sJTzhSmt2AR42bbIApWZk8KmT00RtmQK1ss'
STRIPE_WEBHOOK_SECRET = 'whsec_jtv3Re5tevVlpjhaPszDj8Y0bWVodfoY'



CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis broker
CELERY_RESULT_BACKEND = 'django-db'             # Store task results in DB
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Berlin'


R2_ACCESS_KEY = "c5b0c094a3ad8581e00746d8d7f36873"
R2_SECRET_KEY = "03f7a1c3c586775385f82b966f785b0e87c2d024110bee4320b19f251ca68710"
R2_BUCKET_NAME = "livekit-recordings"
R2_ENDPOINT_URL = "https://25f23cf5d85b78cabf8706e7fa7e6c55.r2.cloudflarestorage.com" 
R2_SIGNED_URL_EXPIRATION = 12000


# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'campusplatz.no.reply@gmail.com'
EMAIL_HOST_PASSWORD = 'rkjexetkhygiverx'
DEFAULT_FROM_EMAIL = 'campusplatz.no.reply@gmail.com'

# Frontend URL for email verification link
FRONTEND_URL = 'http://127.0.0.1:8000/'  # Update this to your frontend URL


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL='/media/'


SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Security settings
SECURE_FILE_UPLOAD = {
    'MAX_SIZE': 4 * 1024 * 1024, 
    'ALLOWED_TYPES': ['image/jpeg', 'image/png', 'application/pdf'],
    #'CDN_MEDIA_URL': 'https://cdn.yourdomain.com/media/'  
}

RECAPTCHA_PUBLIC_KEY = 'YOUR_SITE_KEY'
RECAPTCHA_PRIVATE_KEY = 'YOUR_SECRET_KEY'
RECAPTCHA_REQUIRED_SCORE = 0.85  
RECAPTCHA_ACTION = 'signup' 


LIVEKIT_API_KEY = "APIgaGhNfsBshoX"  
LIVEKIT_API_SECRET = "AHDvf9YF8rDob8v6fJ23D5UAefZT62xR5phWSFPZKgyC" 
LIVEKIT_URL = "https://campusplatz-ckqf7pkr.livekit.cloud"



DAILY_API_URL = "https://api.daily.co/v1"
DAILY_DOMAIN = "deemzcplatz.daily.co"  # Your Daily.co subdomain
DAILY_EMBEDDED_IFRAME = True
DAILY_CO_API_KEY = '6c678ae6df79bddb20d7b635d1d4a8959769346415ab79762f3eff1b8875dc4a'
DAILY_CO_WEBHOOK_SECRET=''
USE_DAILY_CO_FALLBACK = True # set True in production 

FIELD_ENCRYPTION_KEY = '4Uhvh-Y4-y1CuRjERkOYRuqL9F94WPQBt2qvv5Glv_4='

