# Generated by Django 5.1.6 on 2025-04-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclasssession',
            name='Status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='FAILED', max_length=10),
        ),
    ]
