# Generated by Django 5.1.6 on 2025-04-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0002_liveclasssession_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclasssession',
            old_name='Status',
            new_name='status',
        ),
    ]
