# Generated by Django 5.1.6 on 2025-04-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0003_rename_status_liveclasssession_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclasssession',
            old_name='livekit_token_expires',
            new_name='livekit_learner_token_expires',
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='livekit_tutor_token_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
