# Generated by Django 5.1.6 on 2025-04-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0004_rename_livekit_token_expires_liveclasssession_livekit_learner_token_expires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclasssession',
            old_name='fallback_triggered',
            new_name='is_fallback_triggered',
        ),
        migrations.RemoveField(
            model_name='liveclasssession',
            name='fallback_reason',
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='daily_co_learner_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='daily_co_learner_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='daily_co_room_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='daily_co_room_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='daily_co_room_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='daily_co_tutor_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='daily_co_tutor_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='FallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('AUTO', 'System'), ('MANUAL', 'Tutor')], max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_class_streaming.liveclasssession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('screenshare_started', 'Screenshare Started'), ('screenshare_ended', 'Screenshare Ended'), ('recording_started', 'Recording Started'), ('recording_ended', 'Recording Ended'), ('room_created', 'Room Created'), ('room_ended', 'Room Ended')], max_length=20)),
                ('participant_sid', models.CharField(blank=True, max_length=64)),
                ('participant_identity', models.CharField(blank=True, max_length=255)),
                ('participant_role', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_class_streaming.liveclasssession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'event_type'], name='live_class__session_12cab4_idx'), models.Index(fields=['created_at'], name='live_class__created_401f66_idx')],
            },
        ),
    ]
