# Generated by Django 5.1.6 on 2025-04-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0007_liveclasssession_created_at_liveclasssession_date_and_more'),
        ('payments', '0005_remove_payment_availabilities_remove_payment_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclasssession',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_class', to='payments.paymentforliveclass'),
        ),
    ]
