# Generated by Django 5.1.6 on 2025-04-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0010_alter_historicalliveclasssession_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltutorliveclassapisettings',
            name='key_source',
            field=models.CharField(choices=[('PLATFORM', 'Platform Default'), ('CUSTOM', 'Custom Keys')], default='PLATFORM', help_text='Source of API keys for this tutor', max_length=22),
        ),
        migrations.AlterField(
            model_name='tutorliveclassapisettings',
            name='key_source',
            field=models.CharField(choices=[('PLATFORM', 'Platform Default'), ('CUSTOM', 'Custom Keys')], default='PLATFORM', help_text='Source of API keys for this tutor', max_length=22),
        ),
    ]
