# Generated by Django 5.1.6 on 2025-04-17 11:01

import live_class_streaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0011_alter_historicaltutorliveclassapisettings_key_source_and_more'),
        ('payments', '0008_alter_historicalpaymentforcourse_options_and_more'),
        ('users', '0008_alter_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalliveclasssession',
            name='uid',
            field=models.CharField(db_index=True, default=live_class_streaming.models.generate_short_uid, editable=False, help_text='Public session identifier for GDPR-safe sharing', max_length=16),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='uid',
            field=models.CharField(default=live_class_streaming.models.generate_short_uid, editable=False, help_text='Public session identifier for GDPR-safe sharing', max_length=16, unique=True),
        ),
        migrations.AddIndex(
            model_name='liveclasssession',
            index=models.Index(fields=['uid', 'scheduled_start_time'], name='live_class__uid_1c0ab7_idx'),
        ),
    ]
