# Generated by Django 5.1.6 on 2025-04-22 11:36

import live_class_streaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0013_alter_historicalsessioneventlog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalliveclasssession',
            name='uid',
            field=models.CharField(db_index=True, default=live_class_streaming.models.generate_uid_for_live_class, editable=False, help_text='Public session identifier for GDPR-safe sharing', max_length=16),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='uid',
            field=models.CharField(default=live_class_streaming.models.generate_uid_for_live_class, editable=False, help_text='Public session identifier for GDPR-safe sharing', max_length=16, unique=True),
        ),
    ]
