# Generated by Django 5.1.6 on 2025-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0015_historicalliveclassjoinurl_liveclassjoinurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalliveclassjoinurl',
            name='token',
        ),
        migrations.RemoveField(
            model_name='liveclassjoinurl',
            name='token',
        ),
        migrations.AddField(
            model_name='historicalliveclassjoinurl',
            name='learner_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalliveclassjoinurl',
            name='tutor_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclassjoinurl',
            name='learner_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclassjoinurl',
            name='tutor_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
