# Generated by Django 5.1.6 on 2025-04-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0016_remove_historicalliveclassjoinurl_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalliveclassjoinurl',
            old_name='learner_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='liveclassjoinurl',
            old_name='learner_token',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='historicalliveclassjoinurl',
            name='tutor_token',
        ),
        migrations.RemoveField(
            model_name='liveclassjoinurl',
            name='tutor_token',
        ),
    ]
