# Generated by Django 5.1.6 on 2025-04-23 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0017_rename_learner_token_historicalliveclassjoinurl_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalLiveClassJoinURL',
            new_name='HistoricalLiveKitClassJoinURL',
        ),
        migrations.RenameModel(
            old_name='LiveClassJoinURL',
            new_name='LiveKitClassJoinURL',
        ),
        migrations.AlterModelOptions(
            name='historicallivekitclassjoinurl',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical live kit class join url', 'verbose_name_plural': 'historical live kit class join urls'},
        ),
    ]
