# Generated by Django 5.1.6 on 2025-04-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0018_rename_historicalliveclassjoinurl_historicallivekitclassjoinurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallivekitclassjoinurl',
            name='room',
        ),
        migrations.RemoveField(
            model_name='historicallivekitclassjoinurl',
            name='token',
        ),
        migrations.RemoveField(
            model_name='livekitclassjoinurl',
            name='room',
        ),
        migrations.RemoveField(
            model_name='livekitclassjoinurl',
            name='token',
        ),
    ]
