# Generated by Django 5.1.6 on 2025-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0019_remove_historicallivekitclassjoinurl_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalliveclasssession',
            name='livekit_learner_token_expires',
        ),
        migrations.RemoveField(
            model_name='historicalliveclasssession',
            name='livekit_tutor_token_expires',
        ),
        migrations.RemoveField(
            model_name='liveclasssession',
            name='livekit_learner_token_expires',
        ),
        migrations.RemoveField(
            model_name='liveclasssession',
            name='livekit_tutor_token_expires',
        ),
        migrations.AddField(
            model_name='historicalliveclasssession',
            name='livekit_learner_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalliveclasssession',
            name='livekit_tutor_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='livekit_learner_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='livekit_tutor_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
