# Generated by Django 5.1.6 on 2025-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0020_remove_historicalliveclasssession_livekit_learner_token_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsessioneventlog',
            name='event_type',
            field=models.CharField(choices=[('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('track_published', 'Track Published'), ('track_unpublished', 'Track Unpublished'), ('recording_started', 'Recording Started'), ('recording_ended', 'Recording Ended'), ('room_started', 'Room started'), ('room_finished', 'Room finished'), ('ingress_started', 'Ingress Started'), ('ingress_ended', 'Ingress Ended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sessioneventlog',
            name='event_type',
            field=models.CharField(choices=[('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('track_published', 'Track Published'), ('track_unpublished', 'Track Unpublished'), ('recording_started', 'Recording Started'), ('recording_ended', 'Recording Ended'), ('room_started', 'Room started'), ('room_finished', 'Room finished'), ('ingress_started', 'Ingress Started'), ('ingress_ended', 'Ingress Ended')], max_length=20),
        ),
    ]
