# Generated by Django 5.1.6 on 2025-05-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0021_alter_historicalsessioneventlog_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsessionrecording',
            name='local_video_file',
        ),
        migrations.RemoveField(
            model_name='sessionrecording',
            name='local_video_file',
        ),
        migrations.AlterField(
            model_name='historicalsessionrecording',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Recording Started'), ('COMPLETED', 'Recording Completed'), ('FAILED', 'Recording Failed')], default='REQUESTED', max_length=12),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Recording Started'), ('COMPLETED', 'Recording Completed'), ('FAILED', 'Recording Failed')], default='REQUESTED', max_length=12),
        ),
    ]
