# Generated by Django 5.1.6 on 2025-05-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0022_remove_historicalsessionrecording_local_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsessionrecording',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
