# Generated by Django 5.1.6 on 2025-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0023_historicalsessionrecording_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsessionrecording',
            name='encryption_key_id',
        ),
        migrations.RemoveField(
            model_name='sessionrecording',
            name='encryption_key_id',
        ),
        migrations.AddField(
            model_name='historicalsessionrecording',
            name='encryption_algorithm',
            field=models.CharField(default='AES-256', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalsessionrecording',
            name='encyrption_managed_by',
            field=models.CharField(default='CloudFlare R2', max_length=64),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='encryption_algorithm',
            field=models.CharField(default='AES-256', max_length=64),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='encyrption_managed_by',
            field=models.CharField(default='CloudFlare R2', max_length=64),
        ),
    ]
