# Generated by Django 5.1.6 on 2025-06-01 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0024_remove_historicalsessionrecording_encryption_key_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalliveclasssession',
            name='actual_provider',
            field=models.CharField(blank=True, choices=[('LIVEKIT', 'LiveKit'), ('DAILY_CO', 'Daily.co')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalliveclasssession',
            name='primary_provider',
            field=models.CharField(choices=[('LIVEKIT', 'LiveKit'), ('DAILY_CO', 'Daily.co')], default='LIVEKIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalsessionrecording',
            name='retention_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='Days before automatic deletion (GDPR Right to Erasure)', validators=[django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='historicalsessionrecording',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Recording Started'), ('COMPLETED', 'Recording Completed'), ('FAILED', 'Recording Failed')], default='STARTED', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalsessiontelemetry',
            name='provider',
            field=models.CharField(choices=[('LIVEKIT', 'LiveKit'), ('DAILY_CO', 'Daily.co')], max_length=10),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='actual_provider',
            field=models.CharField(blank=True, choices=[('LIVEKIT', 'LiveKit'), ('DAILY_CO', 'Daily.co')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='primary_provider',
            field=models.CharField(choices=[('LIVEKIT', 'LiveKit'), ('DAILY_CO', 'Daily.co')], default='LIVEKIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='retention_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='Days before automatic deletion (GDPR Right to Erasure)', validators=[django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Recording Started'), ('COMPLETED', 'Recording Completed'), ('FAILED', 'Recording Failed')], default='STARTED', max_length=12),
        ),
        migrations.AlterField(
            model_name='sessiontelemetry',
            name='provider',
            field=models.CharField(choices=[('LIVEKIT', 'LiveKit'), ('DAILY_CO', 'Daily.co')], max_length=10),
        ),
    ]
