# Generated by Django 5.1.6 on 2025-03-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('certification_image', models.ImageField(blank=True, null=True, upload_to='live_class_certifications/')),
                ('no_of_classes_required', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorLiveClassProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('topics_covered', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('certifications', models.ManyToManyField(blank=True, related_name='live_class_certitification', to='scheduling_stripe.liveclasscertification')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_profile', to='users.tutor')),
            ],
        ),
    ]
