# Generated by Django 5.1.6 on 2025-03-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0002_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorliveclassprofile',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='beginner', max_length=50),
        ),
    ]
