# Generated by Django 5.1.6 on 2025-03-22 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0003_alter_tutorliveclassprofile_difficulty_level'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorliveclassprofile',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_profile', to='users.tutor'),
        ),
    ]
