# Generated by Django 5.1.6 on 2025-03-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0004_alter_tutorliveclassprofile_tutor'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorliveclassprofile',
            name='learners',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_live_classes', to='users.user'),
        ),
    ]
