# Generated by Django 5.1.6 on 2025-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0005_tutorliveclassprofile_learners'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorliveclassprofile',
            name='learners',
            field=models.ManyToManyField(blank=True, related_name='enrolled_live_classes', to='users.user'),
        ),
    ]
