# Generated by Django 5.1.6 on 2025-03-25 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0006_alter_tutorliveclassprofile_learners'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorLiveClassStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_taught', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('active_students', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('average_rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('current_badge', models.PositiveSmallIntegerField(choices=[(0, 'No Badge'), (1, 'Platz Emerger'), (2, 'Platz Scholar'), (3, 'Platz Master'), (4, 'Platz Legend')], default=0)),
                ('badge_earned_date', models.DateTimeField(blank=True, null=True)),
                ('live_class_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='scheduling_stripe.tutorliveclassprofile')),
            ],
        ),
    ]
