# Generated by Django 5.1.6 on 2025-03-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0007_tutorliveclassstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorliveclassstats',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='tutorliveclassprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
