# Generated by Django 5.1.6 on 2025-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0008_remove_tutorliveclassstats_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorliveclassstats',
            name='active_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorliveclassstats',
            name='classes_taught',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorliveclassstats',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
