# Generated by Django 5.1.6 on 2025-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0009_alter_tutorliveclassstats_active_students_and_more'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorliveclassstats',
            old_name='active_students',
            new_name='active_learners',
        ),
        migrations.RenameField(
            model_name='tutorliveclassstats',
            old_name='total_students',
            new_name='total_learners',
        ),
        migrations.RemoveField(
            model_name='tutorliveclassprofile',
            name='learners',
        ),
        migrations.AddField(
            model_name='tutorliveclassstats',
            name='learners',
            field=models.ManyToManyField(blank=True, related_name='enrolled_live_classes', to='users.user'),
        ),
    ]
