# Generated by Django 5.1.6 on 2025-04-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0010_rename_active_students_tutorliveclassstats_active_learners_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorliveclassprofile',
            old_name='price',
            new_name='price_per_hour',
        ),
    ]
