# Generated by Django 5.1.6 on 2025-04-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0012_historicalliveclasscertification_historicalrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltutorliveclassprofile',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorliveclassprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='live_class_profile_thumbnails/'),
        ),
    ]
