# Generated by Django 5.1.6 on 2025-04-18 17:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_stripe', '0013_historicaltutorliveclassprofile_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltutorliveclassprofile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorliveclassprofile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CatchUpCourseForLiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='course_thumbnails/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='preview_videos/')),
                ('duration', models.CharField(max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='beginner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catch_up_course', to='scheduling_stripe.tutorliveclassprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CatchUpCourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='video_thumbnails/')),
                ('video_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.TimeField(default=None, help_text='Format: HH:MM (e.g., 01:30 for 1 hour 30 mins)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(choices=[('240p', '426x240'), ('360p', '640x360'), ('480p', '854x480'), ('720p', '1280x720')], default='480p', help_text='Current output resolution', max_length=9)),
                ('catch_up_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catch_up_videos', to='scheduling_stripe.catchupcourseforliveclass')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCatchUpCourseForLiveClass',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, max_length=100)),
                ('preview_video', models.TextField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='beginner', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('live_class_profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scheduling_stripe.tutorliveclassprofile')),
            ],
            options={
                'verbose_name': 'historical catch up course for live class',
                'verbose_name_plural': 'historical catch up course for live classs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCatchUpCourseVideo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.TextField(blank=True, max_length=100)),
                ('video_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('video_file', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.TimeField(default=None, help_text='Format: HH:MM (e.g., 01:30 for 1 hour 30 mins)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('resolution', models.CharField(choices=[('240p', '426x240'), ('360p', '640x360'), ('480p', '854x480'), ('720p', '1280x720')], default='480p', help_text='Current output resolution', max_length=9)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('catch_up_course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scheduling_stripe.catchupcourseforliveclass')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical catch up course video',
                'verbose_name_plural': 'historical catch up course videos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
