# Generated by Django 5.2.3 on 2025-06-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptiontier',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
