# Generated by Django 5.2.3 on 2025-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_historicalsubscriptiontier_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptiontier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalsubscriptiontier',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontier',
            unique_together={('service', 'role', 'tier_level')},
        ),
    ]
