# Generated by Django 5.2.3 on 2025-06-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptiontier_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptiontier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='name',
        ),
    ]
