# Generated by Django 5.2.3 on 2025-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_historicalsubscriptiontier_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptiontier',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscriptiontier',
            constraint=models.UniqueConstraint(fields=('service', 'role', 'tier_level'), name='unique_service_role_tier'),
        ),
    ]
