# Generated by Django 5.2.3 on 2025-06-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscriptiontier_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptiontier',
            name='unique_service_role_tier',
        ),
    ]
