# Generated by Django 5.2.3 on 2025-06-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_remove_subscriptiontier_unique_service_role_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptiontier',
            name='tier_level',
            field=models.IntegerField(choices=[(1, 'Platz Basic'), (2, 'Platz Plus'), (3, 'Platz Pro'), (4, 'Platz Advanced'), (5, 'Platz Elite')]),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='tier_level',
            field=models.IntegerField(choices=[(1, 'Platz Basic'), (2, 'Platz Plus'), (3, 'Platz Pro'), (4, 'Platz Advanced'), (5, 'Platz Elite')]),
        ),
        migrations.AddConstraint(
            model_name='subscriptiontier',
            constraint=models.UniqueConstraint(fields=('service', 'role', 'tier_level'), name='unique_service_role_tier'),
        ),
    ]
