# Generated by Django 5.1.6 on 2025-04-09 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0001_initial'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('certification_image', models.ImageField(blank=True, null=True, upload_to='live_class_certifications/')),
                ('no_of_videos_required', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='tutorcourses',
            name='goals',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutorcourses',
            name='preview_video',
            field=models.FileField(blank=True, upload_to='preview_videos/'),
        ),
        migrations.AddField(
            model_name='tutorcourses',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorcourses',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='course_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorcourses',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='tutorcourses',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='live_class_certitification', to='tutor_courses.coursecertification'),
        ),
        migrations.CreateModel(
            name='TutorCoursesStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_learners', models.PositiveIntegerField(default=0)),
                ('total_bought', models.PositiveIntegerField(default=0)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tutor_courses.tutorcourses')),
                ('learners', models.ManyToManyField(blank=True, related_name='enrolled_courses', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tutor_courses.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_courses.tutorcourses')),
            ],
            options={
                'unique_together': {('cart', 'course')},
            },
        ),
    ]
