# Generated by Django 5.1.6 on 2025-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0002_coursecertification_remove_cart_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='duration',
            field=models.TimeField(default=None, help_text='Format: HH:MM (e.g., 01:30 for 1 hour 30 mins)'),
        ),
    ]
