# Generated by Django 5.1.6 on 2025-04-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0003_coursevideo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorcourses',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='course_certitification', to='tutor_courses.coursecertification'),
        ),
        migrations.AlterField(
            model_name='tutorcourses',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='preview_videos/'),
        ),
    ]
