# Generated by Django 5.1.6 on 2025-04-10 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0004_alter_tutorcourses_certifications_and_more'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_learners', to='tutor_courses.tutorcourses')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_courses', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('learner', 'course')},
            },
        ),
    ]
