# Generated by Django 5.1.6 on 2025-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0005_saveforlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='video_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
