# Generated by Django 5.1.6 on 2025-04-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0007_coursespurchased'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='resolution',
            field=models.CharField(choices=[('240p', '426x240'), ('360p', '640x360'), ('480p', '854x480'), ('720p', '1280x720')], default='480p', help_text='Current output resolution', max_length=9),
        ),
        migrations.CreateModel(
            name='CourseVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_duration', models.PositiveIntegerField(default=0, help_text='In seconds')),
                ('completed', models.BooleanField(default=False)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor_courses.tutorcourses')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor_courses.coursevideo')),
            ],
            options={
                'unique_together': {('learner', 'video')},
            },
        ),
    ]
