# Generated by Django 5.1.6 on 2025-04-15 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0008_coursevideo_resolution_coursevideoprogress'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursevideoprogress',
            unique_together={('learner', 'course', 'video')},
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos', models.PositiveIntegerField(default=0)),
                ('completed_videos', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_courses.tutorcourses')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('learner', 'course')},
            },
        ),
    ]
