# Generated by Django 5.1.6 on 2025-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0009_alter_coursevideoprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='last_watched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
