# Generated by Django 5.1.6 on 2025-04-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_courses', '0010_courseprogress_last_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='last_watched_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor_courses.coursevideo'),
        ),
    ]
