# Generated by Django 5.2.3 on 2025-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluniversitydomain',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='universitydomain',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
