# Generated by Django 5.1.6 on 2025-03-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling_stripe', '0006_alter_tutorliveclassprofile_learners'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tutor_currency', models.CharField(max_length=3)),
                ('learner_currency', models.CharField(max_length=3)),
                ('converted_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hours', models.IntegerField()),
                ('additional_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_converted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('eur_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availabilities', models.ManyToManyField(related_name='payments', to='users.availability')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_payments', to='users.user')),
                ('live_class_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='scheduling_stripe.tutorliveclassprofile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_payments', to='users.tutor')),
            ],
        ),
    ]
