# Generated by Django 5.1.6 on 2025-03-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('scheduling_stripe', '0006_alter_tutorliveclassprofile_learners'),
        ('users', '0005_tutor_digital_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_payments', to='users.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='live_class_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='scheduling_stripe.tutorliveclassprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_payments', to='users.tutor'),
        ),
    ]
