# Generated by Django 5.1.6 on 2025-04-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_learner_and_more'),
        ('tutor_courses', '0006_coursevideo_video_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='tutor_base_price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='payment',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='tutor_courses.tutorcourses'),
        ),
    ]
