# Generated by Django 5.1.6 on 2025-04-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_tutor_base_price_payment_base_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_converted_price',
            new_name='converted_total_price',
        ),
        migrations.AddField(
            model_name='payment',
            name='converted_price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
