# Generated by Django 5.1.6 on 2025-04-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_total_converted_price_payment_converted_total_price_and_more'),
        ('scheduling_stripe', '0012_historicalliveclasscertification_historicalrating_and_more'),
        ('tutor_courses', '0012_historicalcart_historicalcartitem_and_more'),
        ('users', '0006_historicalavailability_historicalcertification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='availabilities',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='live_class_profile',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tutor',
        ),
        migrations.CreateModel(
            name='PaymentforCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_currency', models.CharField(max_length=3)),
                ('learner_currency', models.CharField(max_length=3)),
                ('converted_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('converted_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('eur_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='courses', to='tutor_courses.tutorcourses')),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_payments_courses', to='users.user')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_payments_courses', to='users.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentforLiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_currency', models.CharField(max_length=3)),
                ('learner_currency', models.CharField(max_length=3)),
                ('converted_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hours', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('converted_price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('converted_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('eur_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availabilities', models.ManyToManyField(related_name='payments', to='users.availability')),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_payments_live_classes', to='users.user')),
                ('live_class_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='scheduling_stripe.tutorliveclassprofile')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_payments_live_classes', to='users.tutor')),
            ],
        ),
    ]
