# Generated by Django 5.1.6 on 2025-04-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_class_streaming', '0008_alter_liveclasssession_payment'),
        ('payments', '0005_remove_payment_availabilities_remove_payment_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
