# Generated by Django 5.1.6 on 2025-04-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_historicalpaymentforcourse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpaymentforcourse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical payment for course', 'verbose_name_plural': 'historical payment for courses'},
        ),
        migrations.AlterModelOptions(
            name='historicalpaymentforliveclass',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical payment for live class', 'verbose_name_plural': 'historical payment for live classs'},
        ),
    ]
