# Generated by Django 5.1.6 on 2025-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_historicalpaymentforcourse_converted_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentforcourse',
            name='cp_profit',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentforcourse',
            name='eur_revenue',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentforliveclass',
            name='cp_profit',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentforliveclass',
            name='eur_revenue',
        ),
        migrations.RemoveField(
            model_name='paymentforcourse',
            name='cp_profit',
        ),
        migrations.RemoveField(
            model_name='paymentforcourse',
            name='eur_revenue',
        ),
        migrations.RemoveField(
            model_name='paymentforliveclass',
            name='cp_profit',
        ),
        migrations.RemoveField(
            model_name='paymentforliveclass',
            name='eur_revenue',
        ),
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='commission_from_tutor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='cp_profit_from_learner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='net_received_from_stripe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='tutor_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='commission_from_tutor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='cp_profit_from_learner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='net_received_from_stripe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='tutor_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='commission_from_tutor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='cp_profit_from_learner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='net_received_from_stripe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='tutor_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='commission_from_tutor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='cp_profit_from_learner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='net_received_from_stripe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='tutor_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
