# Generated by Django 5.1.6 on 2025-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_historicalpaymentforcourse_cp_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='amount_received_at_stripe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='amount_received_at_stripe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
