# Generated by Django 5.1.6 on 2025-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_historicalpaymentforliveclass_amount_received_at_stripe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaymentforcourse',
            old_name='commission_from_tutor',
            new_name='cp_commission_from_tutor',
        ),
        migrations.RenameField(
            model_name='historicalpaymentforliveclass',
            old_name='commission_from_tutor',
            new_name='cp_commission_from_tutor',
        ),
        migrations.RenameField(
            model_name='paymentforcourse',
            old_name='commission_from_tutor',
            new_name='cp_commission_from_tutor',
        ),
        migrations.RenameField(
            model_name='paymentforliveclass',
            old_name='commission_from_tutor',
            new_name='cp_commission_from_tutor',
        ),
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='cp_total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='cp_total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='cp_total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='cp_total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
