# Generated by Django 5.1.6 on 2025-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_rename_commission_from_tutor_historicalpaymentforcourse_cp_commission_from_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='amount_received_at_stripe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='amount_received_at_stripe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
