# Generated by Django 5.1.6 on 2025-05-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_historicalpaymentforcourse_amount_received_at_stripe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
