# Generated by Django 5.1.6 on 2025-05-08 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_historicalpaymentforcourse_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpaymentforliveclass',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentforliveclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
