# Generated by Django 5.1.6 on 2025-05-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_historicalpaymentforcourse_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentforcourse',
            name='learner_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymentforcourse',
            name='tutor_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymentforliveclass',
            name='learner_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymentforliveclass',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymentforliveclass',
            name='tutor_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentforcourse',
            name='learner_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentforcourse',
            name='tutor_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentforliveclass',
            name='learner_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentforliveclass',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentforliveclass',
            name='tutor_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
