# Generated by Django 5.1.6 on 2025-06-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_historicalpaymentforcourse_additional_charges_and_more'),
        ('tutor_courses', '0012_historicalcart_historicalcartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentforcourse',
            name='courses',
        ),
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tutor_courses.tutorcourses'),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='tutor_courses.tutorcourses'),
        ),
    ]
