# Generated by Django 5.1.6 on 2025-06-04 19:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_paymentforcourse_courses_and_more'),
        ('tutor_courses', '0012_historicalcart_historicalcartitem_and_more'),
        ('users', '0009_alter_historicaluser_password_alter_user_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaymentforcourse',
            old_name='base_price',
            new_name='course_price',
        ),
        migrations.RenameField(
            model_name='historicalpaymentforcourse',
            old_name='total_price',
            new_name='total_course_price',
        ),
        migrations.RenameField(
            model_name='paymentforcourse',
            old_name='base_price',
            new_name='course_price',
        ),
        migrations.RenameField(
            model_name='paymentforcourse',
            old_name='total_price',
            new_name='total_course_price',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentforcourse',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentforliveclass',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='paymentforcourse',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='paymentforliveclass',
            name='exchange_rate',
        ),
        migrations.CreateModel(
            name='CoursePaymentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cp_profit_from_learner', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_received_at_stripe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_received_from_stripe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('courses', models.ManyToManyField(related_name='courses', to='tutor_courses.tutorcourses')),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_payment_group', to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='historicalpaymentforcourse',
            name='course_payment_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.coursepaymentgroup'),
        ),
        migrations.AddField(
            model_name='paymentforcourse',
            name='course_payment_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.coursepaymentgroup'),
        ),
        migrations.CreateModel(
            name='HistoricalCoursePaymentGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cp_profit_from_learner', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_received_at_stripe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_received_from_stripe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user')),
            ],
            options={
                'verbose_name': 'historical course payment group',
                'verbose_name_plural': 'historical course payment groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
