# Generated by Django 5.1.6 on 2025-03-19 17:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('f_name', models.CharField(blank=True, max_length=30, null=True)),
                ('l_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_learner', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
                ('is_google_user', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=32, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0)),
                ('additional_charges', models.FloatField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(null=True, upload_to='profile_photos/')),
                ('address_proof', models.ImageField(upload_to='address_proofs/')),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('designation', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('tutoring_services_description', models.TextField(blank=True, max_length=300, null=True)),
                ('commission_rate', models.FloatField(default=20.0)),
                ('is_premium_user', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('subjects', models.ManyToManyField(related_name='tutors', to='users.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('is_booked', models.BooleanField(default=False)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.CharField(blank=True, max_length=30, null=True)),
                ('campus', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to='users.user')),
            ],
        ),
    ]
