# Generated by Django 5.1.7 on 2025-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tutor_address_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='agreed_terms_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
