# Generated by Django 5.1.6 on 2025-03-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_city_user_country_user_phone_number_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='digital_signature',
            field=models.ImageField(null=True, upload_to='digital_signature/'),
        ),
    ]
