# Generated by Django 5.1.6 on 2025-04-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_historicalavailability_historicalcertification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltutor',
            name='profile_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
