# Generated by Django 5.1.6 on 2025-04-17 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_historicaltutor_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='historicalavailability',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
