# Generated by Django 5.1.6 on 2025-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
